config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :topics, except: [ :index ] do
    resource :answer, only: [ :create, :destroy ]
    resources :comments, only: [ :create, :destroy ]
  end

  devise_for :users
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  extend Enumerize

  belongs_to :topic
  belongs_to :user

  validates_presence_of :topic_id, :user_id, :answer_type

  enumerize :answer_type, in: { unknown: 0, yes: 1, no: -1 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  validates_presence_of :user_id, :topic_id
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend Enumerize

  belongs_to :user
  has_many :answers
  has_many :comments

  validates_presence_of :title, :topic_type

  TOPIC_TYPES = %w(
    会議
    議題
  ).freeze
  enumerize :topic_type, in: TOPIC_TYPES
  validates :topic_type, presence: true, inclusion: { in: TOPIC_TYPES }

  TOPIC_STATES = %w(
    WIP
    OPEN
    CLOSED
  ).freeze
  enumerize :state, in: TOPIC_STATES, default: 'WIP'
  validates :state, presence: true, inclusion: { in: TOPIC_STATES }


  scope :unanswered, ->(user) {
    now = Time.current
    where('start_date > ?', now)
  }

  def num_answer(answer_type)
    self.answers.where(answer_type: answer_type).count
  end

  def num_unknown
    User.count - self.answers.where('answer_type = 1 OR answer_type = -1').count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :topics
  has_many :comments

  validates_presence_of :name

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic
  before_action :set_answer, only: [ :destroy ]

  def create
    @answer = @topic.answers.build(answer_params)
    @answer.user = current_user
    respond_to do |format|
      if @answer.save
        format.html { redirect_to topic_path(@topic), notice: '回答しました。' }
      else
        format.html { redirect_to topic_path(@topic), alert: '回答出来ませんでした。' }
      end
    end
  end

  def destroy
    @answer.destroy!
    redirect_to topic_path(@topic), notice: '回答を取り消しました。'
  end

  private

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    def set_answer
      @answer = @topic.answers.find_by_user_id(current_user)
    end
  
    def answer_params
      params.require(:answer).permit(:answer_type, :message, :topic_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic

  def create
    @comment = @topic.comments.build(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.js
      end
    end
  end

  def destroy
    @comment = @topic.comments.find(params[:id])
    respond_to do |format|
      if @comment.user == current_user
        @comment.destroy!
        format.js
      end
    end
  end

  private

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end

    def comment_params
      params.require(:comment).permit(:topic_id, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [ :edit, :show, :destroy, :update ]

  def new
    @topic = Topic.new(topic_type: params[:topic_type])
  end

  def show
    @answer = @topic.answers.find_by_user_id(current_user)
  end

  def create
    @topic = current_user.topics.create(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to :root, notice: "#{@topic.topic_type}を作成しました。" }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to :root, notice: "更新しました。"}
      else
        format.html { render :edit, alert: "更新できませんでした。" }
      end
    end
  end

  def destroy
    respond_to do |format|
      @topic.destroy!
      format.html { redirect_to :root, notice: '削除しました。' }
    end
  end

  private

    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:topic_type, :title, :start_date, :content, :place, :deadline_date, :state, :end_date)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/answers/_form.html.haml
.topic_state
  = render 'topics/state_label', topic: @topic

- if @topic.state == 'OPEN'
  = simple_form_for [@topic, @topic.answers.new ], url: topic_answer_path(@topic, @answer) do |f|
    .form-inputs
      = f.input :answer_type, as: :radio_buttons, label: '回答'
      = f.input :message, label: 'メッセージ'
    .form-actions
      = f.button :submit, "回答する", class: "btn btn-primary btn-block"

app/views/comments/_comment.html.haml
%tr
  %td= comment.comment
  %td= comment.user.name
  %td= comment.updated_at
  %td
    - if comment.user == current_user
      = link_to [ @topic, comment ], method: :delete, data: { confirm: "削除しますか？" }, class: "text-danger", remote: true do
        %i.glyphicon.glyphicon-remove-sign

app/views/comments/_index.html.haml
%h4 寄せられたコメント

%table.table
  %thead
    %tr
      %th
      %th{style: "width:10em;"}
      %th{style: "width:10em;"}
      %th{style: "width:4em;"}
  %tbody#topic_comments
    = render @topic.comments

%button.btn.btn-success{ data: { toggle: "modal", target: "#topic_comments_modal" } }コメントする

= render 'comments/modal'

app/views/comments/_modal.html.haml
#topic_comments_modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button{ class: "close", data: { dismiss: "modal" }, aria: { hidden: "true" } }☓
        %h4.modal-title コメント

      .modal-body
        = simple_form_for [ @topic, @topic.comments.new ], remote: true do |f|
          = f.input :comment
          = f.button :submit, 'コメント投稿', class: "btn btn-primary"

      .modal-footer
        %button{ class: "btn btn-default", data: { dismiss: "modal" } } Close

app/views/comments/create.js.erb
$('#topic_comments').html("<%= j(render @topic.comments)%>");
$('.modal').modal('hide');

app/views/comments/destroy.js.erb
$('#topic_comments').html("<%= j(render @topic.comments)%>");

app/views/home/index.html.haml
= render 'layouts/menu'
%h1

%ul.nav.nav-tabs{ role: 'tablist' }
  %li{ role: 'presentation', class: 'active' }
    %a{ href: '#unanswered',
        area: { controls: 'unanswered' },
        role: 'tab',
        data: { toggle: 'tab' } } 開催日前のトピックス
  %li{ role: 'presentation' }
    %a{ href: '#my',
        area: { controls: 'my' },
        role: 'tab',
        data: { toggle: 'tab' } } 自分の作ったトピックス


.tab-content
  #unanswered.tab-pane{ role: 'tabpanel' }
    = render 'topics/index', topics: Topic.unanswered(current_user)
  #my.tab-pane{ role: 'tabpanel' }
    = render 'topics/index', topics: current_user.topics.order('updated_at DESC')

app/views/layouts/_header.html.haml
.row
  .col-sm-12
    .navbar.navbar-default
      .container-fluid
        .navbar-header
          = link_to 'Answers', root_path, class: "navbar-brand"
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "#{current_user.name}", edit_user_registration_path
            %li= link_to 'ログアウト', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'ログイン', new_user_session_path

app/views/layouts/_menu.html.haml
.row
  .col-sm-12
    .col-sm-3
      = link_to '会議を招集する', new_topic_path(topic_type: '会議'), class: 'btn btn-primary btn-block'
    .col-sm-3
      = link_to '議題を投稿する', new_topic_path(topic_type: '議題'), class: 'btn btn-success btn-block'
    .col-sm-2
    .col-sm-2
      = link_to '過去の会議を見る', '#', class: 'btn btn-link btn-block', style: "display: none"
    .col-sm-2
      = link_to '過去の議題を見る', '#', class: 'btn btn-link btn-block', style: "display: none"

app/views/layouts/_message.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name == "notice" ? "success" : "danger" }"}
      %button.close{ data: { dismiss: "alert" }, area: { hidden: "true" }, type: "button" } &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Answers
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'

    .container
      .row
        .col-sm-12
          = render 'layouts/message'

      .row
        .col-sm-12
          = yield

app/views/topics/_form.html.haml
= simple_form_for @topic do |f|
  = f.error_notification

  .form-inputs
    = f.input :topic_type, label: 'タイプ'
    = f.input :state, label: '状態'
    = f.input :start_date, label: '開催日'
    = f.input :title, label: 'タイトル'
    = f.input :content, label: '概要'
    = f.input :place, label: '開催場所'
    = f.input :deadline_date, label: '回答締め切り日'

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/topics/_index.html.haml
%table.table
  %thead
    %tr
      %th
      %th 開催日
      %th トピックス
      %th 回答締切日
      %th 参加/全体 (未回答)
      %th
        %i.glyphicon.glyphicon-comment
      %th
  %tbody
    = render topics

app/views/topics/_label.html.haml
%span{ class: "label label-#{topic.topic_type == "会議" ? "primary" : "success" }" }= topic.topic_type

app/views/topics/_state_label.html.haml
- case topic.state
- when 'OPEN'
  - state_label = "info"
- when 'WIP'
  - state_label = "warning"
- when 'CLOSED'
  - state_label = "default"

%span{ class: "label label-#{state_label}" }= topic.state

app/views/topics/_topic.html.haml
%tr
  %td= render 'topics/label', topic: topic
  %td= topic.start_date
  %td
    = render 'topics/state_label', topic: topic
    = link_to topic.title, topic
    - if topic.user == current_user
      = link_to edit_topic_path(topic), class: "text-warning" do
        %i.glyphicon.glyphicon-pencil
  %td= topic.deadline_date
  %td= "#{topic.num_answer(1)}/#{User.all.count} (#{topic.num_unknown})"
  %td= topic.comments.count
  %td
    - if topic.user == current_user
      = link_to topic, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "text-danger" do
        %i.glyphicon.glyphicon-remove-sign

app/views/topics/edit.html.haml
%h2= "#{@topic.title}の編集"

= render 'form'

app/views/topics/new.html.haml
%h2= "新しい#{@topic.topic_type}を作成する"

= render 'form'

app/views/topics/show.html.haml
.row
  .col-sm-10
    .panel.panel-default
      .panel-heading
        = render 'label', topic: @topic
        %h3.panel-title= @topic.title

      .panel-body
        %table.table
          %tr
            %th 開催日
            %td= @topic.start_date
          %tr
            %th 開催場所
            %td= @topic.place
          %tr
            %th 回答締め切り日
            %td= @topic.deadline_date
          %tr
            %th 概要
            %td= @topic.content

  .col-sm-2
    - if @answer.present?
      %h3= @answer.answer_type
      = link_to '回答を取り消す', topic_answer_path(@topic), class: 'btn btn-link btn-block', method: :delete
    - else
      = render 'answers/form'

.row
  .col-sm-12
    %h3 現在の回答状況
    %table.table
      %thead
        %tr
          %th 出席
          %th 欠席
          %th 未回答
      %tbody
        %tr
          %td= @topic.num_answer(1)
          %td= @topic.num_answer(-1)
          %td= @topic.num_unknown

= render 'comments/index'